---

- include: "macos.yml"
  when: ansible_os_family == "Darwin"

- include: "ubuntu.yml"
  when: ansible_distribution == "Ubuntu"

- name: Create .vim directory
  file: path={{ ansible_env.HOME }}/.vim state=directory

- name: Populate .vim directory
  file: path={{ ansible_env.HOME }}/.vim/{{ item }} state=directory
  with_items:
    - bundle
    - colors
    - ftdetect

- name: Clone Vundle.vim
  git:
    repo: https://github.com/VundleVim/Vundle.vim
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

- name: Clone Solarized
  git:
    repo: https://github.com/altercation/vim-colors-solarized
    dest: "{{ ansible_env.HOME }}/.vim/bundle/vim-colors-solarized"

- name: Link Colors
  file:
    src: "{{ ansible_env.HOME }}/.vim/bundle/vim-colors-solarized/colors/solarized.vim"
    dest: "{{ ansible_env.HOME }}/.vim/colors/solarized.vim"
    state: link

- name: Clone My Snippets
  git:
    repo: git@github.com:ryanolson/snips.git
    dest: "{{ ansible_env.HOME }}/.vim/UltiSnips"
    accept_hostkey: yes

- copy: src=vimrc dest={{ ansible_env.HOME }}/.vimrc
  notify:
    - install plugins

- meta: flush_handlers

- command: vim +PluginInstall +qall

- name: Configure YouCompleteMe
  command: ./install.py 
  args:
    chdir: "{{ ansible_env.HOME }}/.vim/bundle/youcompleteme"
    creates: "{{ ansible_env.HOME }}/.vim/bundle/youcompleteme/third_party/ycmd/ycm_core.so"
