---

- name: update apt cache
  apt: update_cache=yes cache_valid_time=600
  become: true

- name: install ubuntu dependencies
  apt: name={{ item }} state=latest
  with_items:
    - vim
    - cmake
    - git
    - python-dev
    - build-essential
  become: true
